"""
Predefined Music AudioMesh presets.
"""

from __future__ import annotations

from typing import Any, Dict, List


DEFAULT_MUSIC_PRESETS: List[Dict[str, Any]] = [
    {
        "name": "Lo-Fi Study Drift",
        "mode": "simple",
        "values": {
            "description": "chill lo-fi study beat with dusty drums, warm tape saturation, and mellow electric piano",
            "instrumental": True,
            "duration": 90,
            "batch_size": 1,
        },
    },
    {
        "name": "Sunrise Acoustic Folk",
        "mode": "simple",
        "values": {
            "description": "uplifting acoustic folk song with fingerpicked guitar, soft percussion, and intimate vocal tone",
            "instrumental": False,
            "vocal_language": "en",
            "duration": 120,
            "batch_size": 1,
        },
    },
    {
        "name": "Neon Night Synthwave",
        "mode": "simple",
        "values": {
            "description": "retro 80s synthwave track with pulsing bass, bright arps, and cinematic city-at-night energy",
            "instrumental": True,
            "duration": 100,
            "batch_size": 2,
        },
    },
    {
        "name": "Indie Pop Roadtrip",
        "mode": "simple",
        "values": {
            "description": "feel-good indie pop anthem with jangly guitars, claps, and catchy singalong chorus",
            "instrumental": False,
            "vocal_language": "en",
            "duration": 110,
            "batch_size": 1,
        },
    },
    {
        "name": "Rainy Day Jazz Lounge",
        "mode": "simple",
        "values": {
            "description": "late-night jazz lounge tune with brushed drums, upright bass, and expressive saxophone lead",
            "instrumental": True,
            "duration": 130,
            "batch_size": 1,
        },
    },
    {
        "name": "Festival EDM Lift",
        "mode": "simple",
        "values": {
            "description": "festival-ready progressive edm build with wide synths, uplifting drops, and crowd energy",
            "instrumental": True,
            "duration": 95,
            "batch_size": 2,
        },
    },
    {
        "name": "Latin Summer Vibes",
        "mode": "simple",
        "values": {
            "description": "sunny latin-pop groove with rhythmic guitars, hand percussion, and breezy beach mood",
            "instrumental": False,
            "vocal_language": "es",
            "duration": 105,
            "batch_size": 1,
        },
    },
    {
        "name": "Dreamy Ambient Sleep",
        "mode": "simple",
        "values": {
            "description": "slow ambient soundscape with airy pads, gentle textures, and deep calming atmosphere",
            "instrumental": True,
            "duration": 180,
            "batch_size": 1,
        },
    },
    {
        "name": "Cinematic Trailer Pulse",
        "mode": "custom",
        "values": {
            "caption": "epic cinematic trailer score with taiko drums, rising strings, and massive brass swells",
            "lyrics": "",
            "bpm": 128,
            "keyscale": "D minor",
            "timesignature": "4",
            "duration": 120,
            "vocal_language": "en",
            "instrumental": True,
            "thinking": True,
            "inference_steps": 12,
            "batch_size": 1,
            "seed": -1,
            "audio_format": "mp3",
        },
    },
    {
        "name": "Midnight RnB Slow Jam",
        "mode": "custom",
        "values": {
            "caption": "modern r&b slow jam with silky vocal runs, lush chords, and deep sub bass",
            "lyrics": "[Verse 1]\nLate city lights fade into blue\nI keep finding every road back to you\n[Chorus]\nHold me close in the midnight glow\nEvery heartbeat says do not let go",
            "bpm": 76,
            "keyscale": "A minor",
            "timesignature": "4",
            "duration": 115,
            "vocal_language": "en",
            "instrumental": False,
            "thinking": True,
            "inference_steps": 10,
            "batch_size": 1,
            "seed": -1,
            "audio_format": "mp3",
        },
    },
    {
        "name": "Boom Bap Storyteller",
        "mode": "custom",
        "values": {
            "caption": "classic boom bap hip hop beat with chopped soul samples, punchy snare, and steady groove",
            "lyrics": "",
            "bpm": 92,
            "keyscale": "E minor",
            "timesignature": "4",
            "duration": 100,
            "vocal_language": "en",
            "instrumental": True,
            "thinking": True,
            "inference_steps": 9,
            "batch_size": 2,
            "seed": -1,
            "audio_format": "mp3",
        },
    },
    {
        "name": "Waltz Piano Noir",
        "mode": "custom",
        "values": {
            "caption": "melancholic piano waltz with dark cinematic strings and old-world ballroom mood",
            "lyrics": "",
            "bpm": 72,
            "keyscale": "D minor",
            "timesignature": "3",
            "duration": 125,
            "vocal_language": "en",
            "instrumental": True,
            "thinking": True,
            "inference_steps": 11,
            "batch_size": 1,
            "seed": -1,
            "audio_format": "wav",
        },
    },
    {
        "name": "City Pop Cruise",
        "mode": "custom",
        "values": {
            "caption": "groovy japanese city pop with funky bass, electric piano, and bright disco rhythm guitars",
            "lyrics": "[Verse 1]\nNeon reflections dance on the bay\nSummer wind carries last night's refrain\n[Chorus]\nDrive all night through a sea of light\nEvery heartbeat shining bright",
            "bpm": 108,
            "keyscale": "C Major",
            "timesignature": "4",
            "duration": 112,
            "vocal_language": "ja",
            "instrumental": False,
            "thinking": True,
            "inference_steps": 10,
            "batch_size": 1,
            "seed": -1,
            "audio_format": "mp3",
        },
    },
    {
        "name": "Acoustic Campfire Ballad",
        "mode": "custom",
        "values": {
            "caption": "heartfelt acoustic campfire ballad with close vocals, harmonies, and soft hand percussion",
            "lyrics": "[Verse 1]\nSmoke in the air and stars overhead\nOld stories wake from words we said\n[Chorus]\nSing it slow where the firelight glows\nHome is wherever this melody goes",
            "bpm": 84,
            "keyscale": "G Major",
            "timesignature": "6",
            "duration": 118,
            "vocal_language": "en",
            "instrumental": False,
            "thinking": True,
            "inference_steps": 9,
            "batch_size": 1,
            "seed": -1,
            "audio_format": "flac",
        },
    },
    {
        "name": "Dark Techno Run",
        "mode": "custom",
        "values": {
            "caption": "driving dark techno with industrial percussion, rolling bassline, and relentless club momentum",
            "lyrics": "",
            "bpm": 132,
            "keyscale": "E minor",
            "timesignature": "4",
            "duration": 96,
            "vocal_language": "en",
            "instrumental": True,
            "thinking": True,
            "inference_steps": 12,
            "batch_size": 2,
            "seed": -1,
            "audio_format": "mp3",
        },
    },
    {
        "name": "Hopeful Pop Espanol",
        "mode": "custom",
        "values": {
            "caption": "hopeful latin pop with airy vocals, rhythmic guitars, and bright radio-ready hook",
            "lyrics": "[Verse 1]\nVuelve la luz cuando te veo llegar\nTodo el invierno se empieza a marchar\n[Chorus]\nSigo cantando para no olvidar\nQue cada herida se puede curar",
            "bpm": 104,
            "keyscale": "A Major",
            "timesignature": "4",
            "duration": 108,
            "vocal_language": "es",
            "instrumental": False,
            "thinking": True,
            "inference_steps": 10,
            "batch_size": 1,
            "seed": -1,
            "audio_format": "mp3",
        },
    },
]
